openapi: 3.0.0
info:
  version: 1.1.0
  title: Biometric time clock
  description: Biometric time clock
servers:
  - url: http://localhost:3055/
    description: Local server (uses local data)
securitySchemes:
  adminToken:
    type: http
    scheme: bearer
    bearerFormat: JWT